name: flouka
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  awesome_snackbar_content: ^0.1.6
  cached_network_image: ^3.4.1
  camera: ^0.10.5+5
  carousel_slider_plus: ^7.1.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  date_picker_timeline: ^1.2.7
  day_night_time_picker: ^1.3.1
  dio: ^5.0.2
  dotted_border: ^3.1.0
  equatable: ^2.0.7
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  flutter:
    sdk: flutter
  flutter_gen: ^5.12.0
  flutter_local_notifications: ^17.2.1
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^4.0.1
  flutter_svg: ^2.2.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  get_it: ^8.0.3
  google_maps_flutter: ^2.5.0
  google_sign_in: ^7.2.0
  image: ^4.5.4
  image_picker: ^1.1.2
  intl: any
  jwt_decode: ^0.3.1
  lottie: ^3.1.2
  path_provider: any
  pick_image: ^1.0.0
  pin_code_fields: ^8.0.1
  pinch_zoom: ^2.0.1
  provider: ^6.1.5
  share_plus: ^12.0.1
  shared_preferences: ^2.1.0
  shimmer: ^3.0.0
  sizer: ^3.0.5
  smooth_page_indicator: ^1.2.1
  store_redirect: ^2.0.4
  time_machine: ^0.9.17
  timeline_tile: ^2.0.0
  url_launcher: ^6.3.2
  voice_message_package: ^2.2.1
  web_socket_channel: ^3.0.3
  webview_flutter: ^4.13.0
  tabby_flutter_inapp_sdk: ^1.11.0
  social_media_recorder: ^1.2.1

dependency_overrides:
  record_platform_interface: 1.2.0
  intl: ^0.20.2
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/address/
    - assets/images/auth/
    - assets/images/categories/
    - assets/images/checkout/
    - assets/images/home/
    - assets/images/navbar/
    - assets/images/onboarding/
    - assets/images/products/
    - assets/images/settings/
    - assets/images/test/
    - assets/images/wallet/
    - assets/fonts/
  # fonts:
  #   - family: Lato
  #     fonts:
  #       - asset: assets/fonts/Lato-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
